import Head from 'next/head'
import Image from 'next/image'
import { AboutMe } from '../components/AboutMe';
import { Contact } from '../components/Contact';
import { Main } from '../components/Main';
import Navbar from '../components/Navbar'
import { Project } from '../components/Project';
import { Skill } from '../components/Skill';

export default function Home({ data }) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Eshan | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar></Navbar>
        <Main></Main>
        <AboutMe></AboutMe>
        <Skill></Skill>
        <Project projects={data}></Project>
        <Contact></Contact>
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:5000/project");
  const data = await res.json();
  return {
    props: {
      data
    }
  }
};